use_retriever:
  description: >
    Retrieve relevant examples from the graph database (GraphDB) using the retriever agent.
    Ensure that the retrieval process is efficient and accurate.
    The retriever agent will search for nodes or entities that closely match the input query (headline).
  expected_output: >
    In this task you should retrieve relevant examples from the graph database for the given text: {headline}.
    Use the available tools to accomplish this task.
    Once you have tried one tool and the output seems satisfactory, do not retry additional tools.
    The task output should be a string representing a list of relevant examples from the graph database.
  agent: retriever_agent

use_tagger:
  description: >
    Identify and tag explicit cause-and-effect relationships in complex sentences using the tagger agent.
    Ensure that the tagging process is systematic and accurate.
    The tagger agent will analyze the structure of sentences to determine the presence of cause, trigger, and effect.
  expected_output: >
    You are an advanced language model tasked with identifying and tagging explicit cause-and-effect relationships in complex sentences.
    Do not modify the original text when adding tags.
    IMPORTANT: Do not provide any output unless all three tags—cause, trigger, and effect—are present in the sentence. If any tag is missing, output "NoTag" and set the label to 0.
    
    Steps:
    1. Causality Determination:
       - Analyze the input sentence to determine if it contains an explicit causal relationship.
       - If the sentence is not causal, output "NoTag" and set the label to 0 without tagging.
       - If the sentence is causal, proceed only if all three elements (cause, trigger, and effect) are present.
       - If any element is missing, output "NoTag" and set the label to 0.
    2. Tagging Instructions:
       - Tag the sentence by enclosing the cause with <cause>...</cause>, the trigger with <trigger>...</trigger>, and the effect with <effect>...</effect>.
       - The cause represents the event or condition leading to an outcome.
       - The trigger is the word or phrase indicating causality (for example, because or due to).
       - The effect is the outcome or result of the cause.
    3. Causality Tests:
       - Ensure that the effect clearly answers "Why?" by directly resulting from the cause.
       - Confirm that the cause precedes the effect in time.
       - Verify that the effect does not occur in the absence of the cause.
       - Check that the cause and effect cannot be interchanged without altering the meaning.
       - The sentence should be rephraseable as "X causes Y" or "Due to X, Y."
    4. Additional Guidelines:
       - The sentence must explicitly state a cause-effect relationship.
       - If there are multiple causes or effects, tag each instance separately.
       - Do not alter the original sentence structure when adding tags.
       - The final output must include all three tags: <cause>, <trigger>, and <effect>.
       - If no explicit causal relationship is found, output "NoTag."
    5. Output Format:
       - Causal Relationship Analysis:
        • Sentence: [Original unmodified sentence]
        • Cause: [Text identified as the cause]
        • Trigger: [Text identified as the causal trigger/verb]
        • Effect: [Text identified as the effect]
        • Label: 1 (Causal relationship present) or 0 (No causal relationship)
        - Example Output:
          {
            "sentence": "[Original unmodified sentence]",
            "cause": "[Text identified as the cause]",
            "trigger": "[Text identified as the causal trigger/verb]",
            "effect": "[Text identified as the effect]",
            "label": 1 (or 0),
            "retriever_examples": [List of examples from the retriever agent]
          }
        - Ensure the output is in JSON format.
        - Example JSON:
          {
            "sentence": "The rain caused the flood.",
            "cause": "The rain",
            "trigger": "caused",
            "effect": "the flood",
            "label": 1,
            "retriever_examples":[
              {
                "example_1": "The heavy rain led to flooding in the area.",
                "cause": "The heavy rain",
                "trigger": "led to",
                "effect": "flooding in the area",
                "label": 1
              },
              {
                  "example_2": "Due to the rain, the river overflowed.",
                  "cause": "the rain",
                  "trigger": "Due to",
                  "effect": "the river overflowed",
                  "label": 1
              },
              //... (up to 20 examples)
              
              - Note: You have to include true retrieved examples here from the retriever agent. And these will be 20 examples. Do not spit out any examples from your own.
          }
        - The output should be clear and structured, making it easy to identify the cause, trigger, and effect.
       
    Examples:
    - For a sentence with a clear causal relationship and all tags present, the output should show the clear tagging of cause, trigger, and effect.
    
    Additionally, include examples from the retriever agent.
    
    QA:
    - For sentences that are tagged as causal, include a brief explanation of the cause-and-effect relationship.
    
    Final Instruction:
    Process the following input text: {headline} and only output JSON which is said in step 5. Do not output anything else.
    Note: Reconsider your decisions step by step internally (chain-of-thought) but do not output your reasoning.
    IMPORTANT: Do not provide any output unless all three tags (cause, trigger, and effect) are present.
  agent: tagger_agent
