use_fact_checker_v1:
  description: >
    Fact check the headline {headline} using the fact checker agent.
    Ensure that the fact-checking process is thorough and reliable.
    The fact checker agent will verify the accuracy of the claims made in the headline.
  expected_output: >
    In this task, you should fact check the headline provided below:
    
    {headline}
  
    Instructions:
      1. Verify the accuracy of each claim in the headline using the available fact-checking tools.
      2. Evaluate and rank the credibility of each source used. Provide a numbered list where "1" represents the most credible source and other sources numbered after which are less credible.
      3. Produce a neat, formatted output (clearly structured text) that includes:
         - A boolean value indicating whether the headline's claims are accurate (True if factually correct, False if not).
         - A numbered list of the sources used, each accompanied by a brief explanation of its credibility.
      4. Do not include any imaginary or unverified data.
      5. Include upto max only 10 credible sources. If you find less then add less but do not exceed 10.
  agent: fact_checker_agent_v1

use_fact_checker_v2:
  description: >
    Fact check the headline {headline} using the fact checker agent.
    Ensure that the fact-checking process is thorough and reliable.
    The fact checker agent will verify the accuracy of the claims made in the headline.
  expected_output: >
    In this task, you should fact check the headline provided below:
    
    {headline}
  
    Instructions:
      1. Verify the accuracy of each claim in the headline using the available fact-checking tools.
      2. Evaluate and rank the credibility of each source used. Provide a numbered list where "1" represents the most credible source and other sources numbered after which are less credible.
      3. Produce a neat, formatted output (clearly structured text) that includes:
         - A boolean value indicating whether the headline's claims are accurate (True if factually correct, False if not).
         - A numbered list of the sources used, each accompanied by a brief explanation of its credibility.
      4. Do not include any imaginary or unverified data.
      5. Include upto max only 10 credible sources. If you find less then add less but do not exceed 10.
  agent: fact_checker_agent_v2

use_source_credibility:
  description: >
    Evaluate the credibility of the sources from fact checker agent using the source credibility agent.
    Ensure that the evaluation process is thorough and reliable.
    The source credibility agent will assess the reliability and trustworthiness of the news outlet.
  expected_output: >
    In this task, you should evaluate the credibility of the sources provided by the fact checker agent.
    
    Instructions:
      1. Assess the reliability and trustworthiness of the news outlet using the available criteria.
      2. Provide a detailed evaluation that includes:
         - A boolean value indicating whether the source is credible (True if credible, False if not).
         - A brief explanation of the criteria used for evaluation.
         - A summary of any potential biases or issues with the source.
      3. Do not include any imaginary or unverified data.
  agent: source_credibility_agent