use_fact_checker_v1:
  description: >
    Fact check the headline {headline} using the fact checker agent.
    Ensure that the fact-checking process is thorough and reliable.
    The fact checker agent will verify the accuracy of the claims made in the headline.
  expected_output: >
    In this task, you should fact check the headline provided below:
    
    {headline}
  
    Instructions:
      1. Verify the accuracy of each claim in the headline using the available fact-checking tools.
      2. Evaluate and rank the credibility of each source used. Provide a numbered list where "1" represents the most credible source and other sources numbered after which are less credible.
      3. Produce a neat, formatted output (clearly structured text) that includes:
         - A boolean value indicating whether the headline's claims are accurate (True if factually correct, False if not).
         - A numbered list of the sources used, each accompanied by a brief explanation of its credibility.
      4. Do not include any imaginary or unverified data.
      5. Include upto max only 10 credible sources. If you find less then add less but do not exceed 10.
  agent: fact_checker_agent_v1

use_fact_checker_v2:
  description: >
    Fact check the headline {headline} using the fact checker agent.
    Ensure that the fact-checking process is thorough and reliable.
    The fact checker agent will verify the accuracy of the claims made in the headline.
  expected_output: >
    In this task, you should fact check the headline provided below:
    
    {headline}
  
    Instructions:
      1. Verify the accuracy of each claim in the headline using the available fact-checking tools.
      2. Evaluate and rank the credibility of each source used. Provide a numbered list where "1" represents the most credible source and other sources numbered after which are less credible.
      3. Produce a neat, formatted output (clearly structured text) that includes:
         - A boolean value indicating whether the headline's claims are accurate (True if factually correct, False if not).
         - A numbered list of the sources used, each accompanied by a brief explanation of its credibility.
      4. Do not include any imaginary or unverified data.
      5. Include upto max only 10 credible sources. If you find less then add less but do not exceed 10.
  agent: fact_checker_agent_v2

use_source_credibility:
  description: >
    Evaluate the credibility of the sources from fact checker agent using the source credibility agent.
    Ensure that the evaluation process is thorough and reliable.
    The source credibility agent will assess the reliability and trustworthiness of the news outlet.
  expected_output: >
    ## Source Credibility Evaluation

    ### Verified Legitimate Sources:
    - [Source Name 1]: Rating: [High/Medium/Low] credibility
      - Publication type: [Mainstream news/Academic/Government/etc.]
      - Notable features: [Fact-checking practices, editorial standards, etc.]

    - [Source Name 2]: Rating: [High/Medium/Low] credibility
      - Publication type: [Mainstream news/Academic/Government/etc.]
      - Notable features: [Fact-checking practices, editorial standards, etc.]

    - [Source Name 3]: Rating: [High/Medium/Low] credibility
      - Publication type: [Mainstream news/Academic/Government/etc.]
      - Notable features: [Fact-checking practices, editorial standards, etc.]

    ### Headline Verification:
    - Original headline: "[Exact headline as provided]"
    - Headline accuracy: [Confirmed/Partially accurate/Not accurate]
    - Supporting evidence: [Brief summary of how the sources confirm or contradict the headline]

    ### Summary Assessment:
    Based on evaluation of the credible sources above, this news item is [VERIFIED/PARTIALLY VERIFIED/NOT VERIFIED]. 

    [2-3 sentence explanation of why these sources are considered reliable and how they collectively support or refute the headline's claims.]
  agent: source_credibility_agent
